### ISSUE TITLE
Though I should share the insights I found in your code..

### ISSUE THREAD

**Issue by sahilrajput03** [I-keep-trying/fullstackopen-exercises#6]
## Made that list on notepad, coz I myself doing grapqhl again, and was recalling things learned earlier, kinda forgot some thing, might help you. 
@Andrea 

• That approach is isn't the right way to handler error!!
```
    createBook(bookObject).catch((e) => {
      console.log('##new book error', e)
      if (bookObject.variables.author.length < 4) {
        setMessage('Author name must be 4 characters minimum.')
        setTimeout(() => {
          setMessage(null)
        }, 5000)
      } else if (bookObject.variables.title.length < 2) {
        setMessage('Book Title must be 2 characters minimum.')
        setTimeout(() => {
          setMessage(null)
        }, 5000)
      } else if (e.networkError) {
        setMessage('Title, Author, and Published date are required.')
        setTimeout(() => {
          setMessage(null)
        }, 5000)
      } else if (e.errors) {
        console.log('error .catch', e)
      }
    }) // createBook mutation handler ends here.
```

![193735](https://user-images.githubusercontent.com/31458531/95490624-153dc680-09b6-11eb-9b2b-b1203495142d.png)

Instead, it should be done like in #img, error in mutations must only be handled like in this `createPerson` in course.

• New Book.js (made bigger changes..) ##send whole component.js file...

• Found this line in Book.js @ line 19, you have this..
{books.map((book) => {
console.log('mapped book',book)
//POINT1: must return something here...
      })}
//POINT2: In ui, when we click on `Books` tab code was throwing error like, .map is not a function, so what can we do ??
Just put a question mark there, and js will do the property check on that, and will only call map function if `map` really exists on that data structure.
That solves it for an instant, but you need to see why books is not an array(coz only array have map methods).

• And in UI, when I click on `Authors` tab, code throws error  from => Authors.js file, @ line : 4, i.e., `Cannot read property 'allAuthors' of undefined` in ui.
`authors = authors.data.allAuthors`
so, we can simply put a question mark that'll do property check AGAIN.
like: 
`authors = authors.data?.allAuthors`
and its pathed for the instant, but we need to see log, why debug
why we are getting `allAuthors` as `undefined` ..., 

•Recommended article to read: https://kentcdodds.com/blog/javascript-to-know-for-react/
There's nullish collasence operator and property check operator iirc.

**Comment by I-keep-trying** [comment]
which repo is this about?

**Comment by I-keep-trying** [comment]
First of all, you made this comment 8 days ago. I did not submit my final repo until late yesterday. 

If you are looking at anything before then, WHO KNOWS what weird things you will see. I make commits randomly throughout development, some things might not be anywhere near finished. 

> • That approach is isn't the right way to handler error!!
> 

What approach? What code are you looking at? Please show me the error handler you are referring to. 

> ```
>     createBook(bookObject).catch((e) => {
>       console.log('##new book error', e)
>       if (bookObject.variables.author.length < 4) {
>         setMessage('Author name must be 4 characters minimum.')
>         setTimeout(() => {
>           setMessage(null)
>         }, 5000)
>       } else if (bookObject.variables.title.length < 2) {
>         setMessage('Book Title must be 2 characters minimum.')
>         setTimeout(() => {
>           setMessage(null)
>         }, 5000)
>       } else if (e.networkError) {
>         setMessage('Title, Author, and Published date are required.')
>         setTimeout(() => {
>           setMessage(null)
>         }, 5000)
>       } else if (e.errors) {
>         console.log('error .catch', e)
>       }
>     }) // createBook mutation handler ends here.
> ```
> 

I don't recognize this, is this in my repo somewhere? 

> Instead, it should be done like in #img, error in mutations must only be handled like in this `createPerson` in course.
> 

That is exactly how I did mine. 

It is a waste of both of our time for you to be snooping through my code line by line looking for mistakes, if it has not been submitted yet. OF COURSE you will find things that are wrong. IT WASN'T FINISHED.

**Comment by sahilrajput03** [comment]
Cool, you fixed all those things after we had a chat on fso group. Its 100% fine now I think.
Thanks for replying though. :)
